### ISSUE TITLE
Write explanation about how the compiler works

### ISSUE THREAD

**Issue by nathanfallet** [jacobp100/reasonml-playground-native#4]
I find the idea interesting to use javascript to build the code and run it. It could be awesome to create a markdown file to explain how the `runtime` part works (with how the reason/ocaml static part was generated, I saw it was using js_of_ocaml but it's not explained at all)

**Comment by jacobp100** [comment]
I don't know how the reason and ocaml compiler was generated. I took it from https://reasonml.github.io/en/try

I probably won't get round to writing an explanation, but if you need any pointers, I'm happy to help 😀

**Comment by nathanfallet** [comment]
Got it to work, that's perfect
